ALTER TABLE Review ADD CONSTRAINT pk_review_Id PRIMARY KEY (id);

ALTER TABLE Usuario ADD CONSTRAINT pk_usuario_Id PRIMARY KEY (id);

ALTER TABLE Amenity ADD CONSTRAINT pk_amenity_Id PRIMARY KEY (id);

ALTER TABLE State ADD CONSTRAINT pk_states_Id PRIMARY KEY (amenity_id);

ALTER TABLE City ADD CONSTRAINT pk_city_Id PRIMARY KEY (id);

ALTER TABLE Place ADD CONSTRAINT pk_place_Id PRIMARY KEY (id);