
CREATE USER C##airbnbA 
IDENTIFIED BY admin
DEFAULT TABLESPACE SYSTEM
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON SYSTEM;

GRANT CREATE USER TO C##ADRIAN;

GRANT CREATE SESSION TO C##airbnbA ;


GRANT SELECT ON SYSTEM.CITY TO C##airbnbA;
GRANT SELECT ON SYSTEM.REVIEW TO C##airbnbA;
GRANT SELECT ON SYSTEM.PLACE TO C##airbnbA;
GRANT SELECT ON SYSTEM.USUARIO TO C##airbnbA;
GRANT SELECT ON SYSTEM.STATE TO C##airbnbA;
GRANT SELECT ON SYSTEM.AMENITY TO C##airbnbA;
GRANT SELECT ON SYSTEM.STATE TO C##airbnbA;
GRANT SELECT ON SYSTEM.PLACEAMENITY TO C##airbnbA;

GRANT CREATE TABLE TO C##airbnbA;

GRANT CREATE SESSION TO C##ADMIN;-- PARA INICIAR SESSION    
GRANT CREATE TABLE TO C##ADMIN;-- PARA CREAR TABLA
GRANT CREATE VIEW TO C##ADMIN;-- PARA CREAR VISTA
GRANT CREATE SEQUENCE TO C##ADMIN;-- PARA CREAR SEQUENCIA


---Crear un usuario adicional (Dejar el script .sql de creación y privilegios)

CREATE USER C##userAddNuevo 
IDENTIFIED BY admin
DEFAULT TABLESPACE SYSTEM
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON SYSTEM;

---Crear privilegios de acceso a sus datos (Dejar privilegios en archivo .sql)

GRANT CREATE SESSION TO C##userAddNuevo  ;

GRANT SELECT ON SYSTEM.CITY TO C##userAddNuevo ;
GRANT SELECT ON SYSTEM.REVIEW TO C##userAddNuevo;
GRANT SELECT ON SYSTEM.PLACE TO C##userAddNuevo;
GRANT SELECT ON SYSTEM.USUARIO TO C##userAddNuevo;
GRANT SELECT ON SYSTEM.STATE TO C##userAddNuevo;
GRANT SELECT ON SYSTEM.AMENITY TO C##userAddNuevo;
GRANT SELECT ON SYSTEM.PLACEAMENITY TO C##userAddNuevo;

GRANT ALL PRIVILEGES TO C##userAddNuevo;













